package jp.co.suyama.menu.deliver.mapper.auto;

import java.util.List;
import jp.co.suyama.menu.deliver.model.db.Bounce;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface BounceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	@Delete({ "delete from bounce", "where user_id = #{userId,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	@Insert({ "insert into bounce (user_id, bounce)", "values (#{userId,jdbcType=INTEGER}, #{bounce,jdbcType=BIT})" })
	int insert(Bounce record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	@Select({ "select", "user_id, bounce", "from bounce", "where user_id = #{userId,jdbcType=INTEGER}" })
	@Results({ @Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "bounce", property = "bounce", jdbcType = JdbcType.BIT) })
	Bounce selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	@Select({ "select", "user_id, bounce", "from bounce" })
	@Results({ @Result(column = "user_id", property = "userId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "bounce", property = "bounce", jdbcType = JdbcType.BIT) })
	List<Bounce> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	@Update({ "update bounce", "set bounce = #{bounce,jdbcType=BIT}", "where user_id = #{userId,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Bounce record);
}