package jp.co.suyama.menu.deliver.mapper.auto;

import java.util.List;
import jp.co.suyama.menu.deliver.model.db.MenuCompositions;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface MenuCompositionsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_compositions
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	@Delete({ "delete from menu_compositions", "where menu_id = #{menuId,jdbcType=INTEGER}",
			"and composition_item_no = #{compositionItemNo,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(@Param("menuId") Integer menuId, @Param("compositionItemNo") Integer compositionItemNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_compositions
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	@Insert({ "insert into menu_compositions (menu_id, composition_item_no)",
			"values (#{menuId,jdbcType=INTEGER}, #{compositionItemNo,jdbcType=INTEGER})" })
	int insert(MenuCompositions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_compositions
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	@Select({ "select", "menu_id, composition_item_no", "from menu_compositions" })
	@Results({ @Result(column = "menu_id", property = "menuId", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "composition_item_no", property = "compositionItemNo", jdbcType = JdbcType.INTEGER, id = true) })
	List<MenuCompositions> selectAll();
}