package jp.co.suyama.menu.deliver.mapper.auto;

import java.util.List;
import jp.co.suyama.menu.deliver.model.db.MenuPictures;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface MenuPicturesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_pictures
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	@Delete({ "delete from menu_pictures", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_pictures
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	@Insert({ "insert into menu_pictures (id, menu_id, ", "path, order_of, created_at, ", "updated_at)",
			"values (#{id,jdbcType=INTEGER}, #{menuId,jdbcType=INTEGER}, ",
			"#{path,jdbcType=VARCHAR}, #{orderOf,jdbcType=INTEGER}, #{createdAt,jdbcType=TIMESTAMP}, ",
			"#{updatedAt,jdbcType=TIMESTAMP})" })
	int insert(MenuPictures record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_pictures
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	@Select({ "select", "id, menu_id, path, order_of, created_at, updated_at", "from menu_pictures",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "menu_id", property = "menuId", jdbcType = JdbcType.INTEGER),
			@Result(column = "path", property = "path", jdbcType = JdbcType.VARCHAR),
			@Result(column = "order_of", property = "orderOf", jdbcType = JdbcType.INTEGER),
			@Result(column = "created_at", property = "createdAt", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_at", property = "updatedAt", jdbcType = JdbcType.TIMESTAMP) })
	MenuPictures selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_pictures
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	@Select({ "select", "id, menu_id, path, order_of, created_at, updated_at", "from menu_pictures" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "menu_id", property = "menuId", jdbcType = JdbcType.INTEGER),
			@Result(column = "path", property = "path", jdbcType = JdbcType.VARCHAR),
			@Result(column = "order_of", property = "orderOf", jdbcType = JdbcType.INTEGER),
			@Result(column = "created_at", property = "createdAt", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_at", property = "updatedAt", jdbcType = JdbcType.TIMESTAMP) })
	List<MenuPictures> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu_pictures
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	@Update({ "update menu_pictures", "set menu_id = #{menuId,jdbcType=INTEGER},", "path = #{path,jdbcType=VARCHAR},",
			"order_of = #{orderOf,jdbcType=INTEGER},", "created_at = #{createdAt,jdbcType=TIMESTAMP},",
			"updated_at = #{updatedAt,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(MenuPictures record);
}