package jp.co.suyama.menu.deliver.mapper.auto;

import java.util.List;
import jp.co.suyama.menu.deliver.model.db.RecommendArticles;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface RecommendArticlesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recommend_articles
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	@Delete({ "delete from recommend_articles", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recommend_articles
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	@Insert({ "insert into recommend_articles (id, path, ", "content, created_at, ", "updated_at)",
			"values (#{id,jdbcType=INTEGER}, #{path,jdbcType=VARCHAR}, ",
			"#{content,jdbcType=VARCHAR}, #{createdAt,jdbcType=TIMESTAMP}, ", "#{updatedAt,jdbcType=TIMESTAMP})" })
	int insert(RecommendArticles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recommend_articles
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	@Select({ "select", "id, path, content, created_at, updated_at", "from recommend_articles",
			"where id = #{id,jdbcType=INTEGER}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "path", property = "path", jdbcType = JdbcType.VARCHAR),
			@Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_at", property = "createdAt", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_at", property = "updatedAt", jdbcType = JdbcType.TIMESTAMP) })
	RecommendArticles selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recommend_articles
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	@Select({ "select", "id, path, content, created_at, updated_at", "from recommend_articles" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "path", property = "path", jdbcType = JdbcType.VARCHAR),
			@Result(column = "content", property = "content", jdbcType = JdbcType.VARCHAR),
			@Result(column = "created_at", property = "createdAt", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "updated_at", property = "updatedAt", jdbcType = JdbcType.TIMESTAMP) })
	List<RecommendArticles> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table recommend_articles
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	@Update({ "update recommend_articles", "set path = #{path,jdbcType=VARCHAR},",
			"content = #{content,jdbcType=VARCHAR},", "created_at = #{createdAt,jdbcType=TIMESTAMP},",
			"updated_at = #{updatedAt,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(RecommendArticles record);
}