spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/menu_deliver
    username: postgres
    password: postgres

server:
  port: 48080
  servlet:
    context-path: /api

logging:
  level:
    jp.co.suyama.menu.deliver.mapper: DEBUG

mail:
  from: info@menu-deliver.work

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

domain: menu-deliver.work

---
spring:
  profiles: development

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

mail:
  from: info@menu-deliver.work

---
spring:
  profiles: product

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

mail:
  from: info@menu-deliver.com

domain: menu-deliver.com