spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/menu_deliver
    username: postgres
    password: postgres
  servlet:
    multipart:
      # デフォルトのMultipartResolverの有効性
      enabled: true
      # アップロード時の1つのファイルサイズの上限
      max-file-size: 20MB
      # リクエストの全体のサイズの上限
      max-request-size: 100MB
      # アップロードしたファイルがサーバーのディスクに書き込まれるファイルサイズの閾値
      file-size-threshold: 50MB

server:
  port: 48080
  servlet:
    context-path: /api
    session:
      timeout: 1440m
      cookie:
        secure: true
        http-only: true

logging:
  level:
    jp.co.suyama.menu.deliver.mapper: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

mail:
  from: info@menu-deliver.local

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}

domain: http://localhost:8080

---
spring:
  profiles: development

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

mail:
  from: info@menu-deliver.work
  
domain: https://www.menu-deliver.work

---
spring:
  profiles: product

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

mail:
  from: info@menu-deliver.com

domain: https://www.menu-deliver.com