package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class AnswerImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_images.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_images.answer_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_images.path
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_images.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column answer_images.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_images.id
     *
     * @return the value of answer_images.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_images.id
     *
     * @param id the value for answer_images.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_images.answer_id
     *
     * @return the value of answer_images.answer_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_images.answer_id
     *
     * @param answerId the value for answer_images.answer_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_images.path
     *
     * @return the value of answer_images.path
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_images.path
     *
     * @param path the value for answer_images.path
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_images.created_at
     *
     * @return the value of answer_images.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_images.created_at
     *
     * @param createdAt the value for answer_images.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column answer_images.updated_at
     *
     * @return the value of answer_images.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column answer_images.updated_at
     *
     * @param updatedAt the value for answer_images.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}