package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class Articles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.user_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.title
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.start_sentence
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private String startSentence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.opened
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Boolean opened;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.created_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column articles.updated_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.id
	 * @return  the value of articles.id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.id
	 * @param id  the value for articles.id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.user_id
	 * @return  the value of articles.user_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.user_id
	 * @param userId  the value for articles.user_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.title
	 * @return  the value of articles.title
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.title
	 * @param title  the value for articles.title
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.start_sentence
	 * @return  the value of articles.start_sentence
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public String getStartSentence() {
		return startSentence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.start_sentence
	 * @param startSentence  the value for articles.start_sentence
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setStartSentence(String startSentence) {
		this.startSentence = startSentence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.opened
	 * @return  the value of articles.opened
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Boolean getOpened() {
		return opened;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.opened
	 * @param opened  the value for articles.opened
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setOpened(Boolean opened) {
		this.opened = opened;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.created_at
	 * @return  the value of articles.created_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.created_at
	 * @param createdAt  the value for articles.created_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column articles.updated_at
	 * @return  the value of articles.updated_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column articles.updated_at
	 * @param updatedAt  the value for articles.updated_at
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}