package jp.co.suyama.menu.deliver.model.db;

public class Bounce {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bounce.user_id
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bounce.bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	private Boolean bounce;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bounce.user_id
	 * @return  the value of bounce.user_id
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bounce.user_id
	 * @param userId  the value for bounce.user_id
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bounce.bounce
	 * @return  the value of bounce.bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	public Boolean getBounce() {
		return bounce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bounce.bounce
	 * @param bounce  the value for bounce.bounce
	 * @mbg.generated  Fri Mar 26 16:41:36 JST 2021
	 */
	public void setBounce(Boolean bounce) {
		this.bounce = bounce;
	}
}