package jp.co.suyama.menu.deliver.model.db;

public class Compositions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.item_no
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Integer itemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.item_group
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Integer itemGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.item_index
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Integer itemIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.name
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.energy
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double energy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.protein
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double protein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.lipid
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double lipid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.carbohydrate
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double carbohydrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.calcium
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double calcium;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.iron
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double iron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.cholesterol
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double cholesterol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.dietary_fibers
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double dietaryFibers;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.salt_equivalents
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double saltEquivalents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column compositions.refuse
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    private Double refuse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.item_no
     *
     * @return the value of compositions.item_no
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Integer getItemNo() {
        return itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.item_no
     *
     * @param itemNo the value for compositions.item_no
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setItemNo(Integer itemNo) {
        this.itemNo = itemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.item_group
     *
     * @return the value of compositions.item_group
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Integer getItemGroup() {
        return itemGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.item_group
     *
     * @param itemGroup the value for compositions.item_group
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setItemGroup(Integer itemGroup) {
        this.itemGroup = itemGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.item_index
     *
     * @return the value of compositions.item_index
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Integer getItemIndex() {
        return itemIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.item_index
     *
     * @param itemIndex the value for compositions.item_index
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setItemIndex(Integer itemIndex) {
        this.itemIndex = itemIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.name
     *
     * @return the value of compositions.name
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.name
     *
     * @param name the value for compositions.name
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.energy
     *
     * @return the value of compositions.energy
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getEnergy() {
        return energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.energy
     *
     * @param energy the value for compositions.energy
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setEnergy(Double energy) {
        this.energy = energy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.protein
     *
     * @return the value of compositions.protein
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getProtein() {
        return protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.protein
     *
     * @param protein the value for compositions.protein
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setProtein(Double protein) {
        this.protein = protein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.lipid
     *
     * @return the value of compositions.lipid
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getLipid() {
        return lipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.lipid
     *
     * @param lipid the value for compositions.lipid
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setLipid(Double lipid) {
        this.lipid = lipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.carbohydrate
     *
     * @return the value of compositions.carbohydrate
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getCarbohydrate() {
        return carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.carbohydrate
     *
     * @param carbohydrate the value for compositions.carbohydrate
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setCarbohydrate(Double carbohydrate) {
        this.carbohydrate = carbohydrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.calcium
     *
     * @return the value of compositions.calcium
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getCalcium() {
        return calcium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.calcium
     *
     * @param calcium the value for compositions.calcium
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setCalcium(Double calcium) {
        this.calcium = calcium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.iron
     *
     * @return the value of compositions.iron
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getIron() {
        return iron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.iron
     *
     * @param iron the value for compositions.iron
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setIron(Double iron) {
        this.iron = iron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.cholesterol
     *
     * @return the value of compositions.cholesterol
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getCholesterol() {
        return cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.cholesterol
     *
     * @param cholesterol the value for compositions.cholesterol
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setCholesterol(Double cholesterol) {
        this.cholesterol = cholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.dietary_fibers
     *
     * @return the value of compositions.dietary_fibers
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getDietaryFibers() {
        return dietaryFibers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.dietary_fibers
     *
     * @param dietaryFibers the value for compositions.dietary_fibers
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setDietaryFibers(Double dietaryFibers) {
        this.dietaryFibers = dietaryFibers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.salt_equivalents
     *
     * @return the value of compositions.salt_equivalents
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getSaltEquivalents() {
        return saltEquivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.salt_equivalents
     *
     * @param saltEquivalents the value for compositions.salt_equivalents
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setSaltEquivalents(Double saltEquivalents) {
        this.saltEquivalents = saltEquivalents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column compositions.refuse
     *
     * @return the value of compositions.refuse
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public Double getRefuse() {
        return refuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column compositions.refuse
     *
     * @param refuse the value for compositions.refuse
     *
     * @mbg.generated Wed Mar 24 23:59:44 JST 2021
     */
    public void setRefuse(Double refuse) {
        this.refuse = refuse;
    }
}