package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class Followers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followers.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followers.user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followers.follower_user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer followerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followers.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column followers.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followers.id
     *
     * @return the value of followers.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followers.id
     *
     * @param id the value for followers.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followers.user_id
     *
     * @return the value of followers.user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followers.user_id
     *
     * @param userId the value for followers.user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followers.follower_user_id
     *
     * @return the value of followers.follower_user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getFollowerUserId() {
        return followerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followers.follower_user_id
     *
     * @param followerUserId the value for followers.follower_user_id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setFollowerUserId(Integer followerUserId) {
        this.followerUserId = followerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followers.created_at
     *
     * @return the value of followers.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followers.created_at
     *
     * @param createdAt the value for followers.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column followers.updated_at
     *
     * @return the value of followers.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column followers.updated_at
     *
     * @param updatedAt the value for followers.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}