package jp.co.suyama.menu.deliver.model.db;

public class MenuCompositions {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_compositions.menu_id
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	private Integer menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_compositions.composition_item_no
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	private Integer compositionItemNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_compositions.menu_id
	 * @return  the value of menu_compositions.menu_id
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_compositions.menu_id
	 * @param menuId  the value for menu_compositions.menu_id
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_compositions.composition_item_no
	 * @return  the value of menu_compositions.composition_item_no
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	public Integer getCompositionItemNo() {
		return compositionItemNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_compositions.composition_item_no
	 * @param compositionItemNo  the value for menu_compositions.composition_item_no
	 * @mbg.generated  Sun Mar 28 19:25:54 JST 2021
	 */
	public void setCompositionItemNo(Integer compositionItemNo) {
		this.compositionItemNo = compositionItemNo;
	}
}