package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class MenuViews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_views.menu_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Integer menuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_views.date
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column menu_views.count
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	private Integer count;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_views.menu_id
	 * @return  the value of menu_views.menu_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_views.menu_id
	 * @param menuId  the value for menu_views.menu_id
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_views.date
	 * @return  the value of menu_views.date
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_views.date
	 * @param date  the value for menu_views.date
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column menu_views.count
	 * @return  the value of menu_views.count
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public Integer getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column menu_views.count
	 * @param count  the value for menu_views.count
	 * @mbg.generated  Fri Mar 19 20:01:37 JST 2021
	 */
	public void setCount(Integer count) {
		this.count = count;
	}
}