package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class Questions {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.user_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.contents
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private String contents;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.answer_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer answerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column questions.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.id
	 * @return  the value of questions.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.id
	 * @param id  the value for questions.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.user_id
	 * @return  the value of questions.user_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.user_id
	 * @param userId  the value for questions.user_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.contents
	 * @return  the value of questions.contents
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public String getContents() {
		return contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.contents
	 * @param contents  the value for questions.contents
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setContents(String contents) {
		this.contents = contents;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.answer_id
	 * @return  the value of questions.answer_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getAnswerId() {
		return answerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.answer_id
	 * @param answerId  the value for questions.answer_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.created_at
	 * @return  the value of questions.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.created_at
	 * @param createdAt  the value for questions.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column questions.updated_at
	 * @return  the value of questions.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column questions.updated_at
	 * @param updatedAt  the value for questions.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}