package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class QuestionImages {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_images.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_images.question_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer questionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_images.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_images.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column question_images.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_images.id
	 * @return  the value of question_images.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_images.id
	 * @param id  the value for question_images.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_images.question_id
	 * @return  the value of question_images.question_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_images.question_id
	 * @param questionId  the value for question_images.question_id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_images.path
	 * @return  the value of question_images.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_images.path
	 * @param path  the value for question_images.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_images.created_at
	 * @return  the value of question_images.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_images.created_at
	 * @param createdAt  the value for question_images.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column question_images.updated_at
	 * @return  the value of question_images.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column question_images.updated_at
	 * @param updatedAt  the value for question_images.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}