package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class RecommendArticles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommend_articles.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommend_articles.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private String path;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommend_articles.content
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommend_articles.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column recommend_articles.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	private Date updatedAt;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommend_articles.id
	 * @return  the value of recommend_articles.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommend_articles.id
	 * @param id  the value for recommend_articles.id
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommend_articles.path
	 * @return  the value of recommend_articles.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public String getPath() {
		return path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommend_articles.path
	 * @param path  the value for recommend_articles.path
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommend_articles.content
	 * @return  the value of recommend_articles.content
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommend_articles.content
	 * @param content  the value for recommend_articles.content
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommend_articles.created_at
	 * @return  the value of recommend_articles.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommend_articles.created_at
	 * @param createdAt  the value for recommend_articles.created_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column recommend_articles.updated_at
	 * @return  the value of recommend_articles.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column recommend_articles.updated_at
	 * @param updatedAt  the value for recommend_articles.updated_at
	 * @mbg.generated  Wed Mar 24 14:49:18 JST 2021
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}
}