package jp.co.suyama.menu.deliver.model.db;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.icon
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.available
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.once_password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private String oncePassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.expires
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date expires;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.deleted
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.icon
     *
     * @return the value of users.icon
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.icon
     *
     * @param icon the value for users.icon
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.available
     *
     * @return the value of users.available
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.available
     *
     * @param available the value for users.available
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.once_password
     *
     * @return the value of users.once_password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public String getOncePassword() {
        return oncePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.once_password
     *
     * @param oncePassword the value for users.once_password
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setOncePassword(String oncePassword) {
        this.oncePassword = oncePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.expires
     *
     * @return the value of users.expires
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.expires
     *
     * @param expires the value for users.expires
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setExpires(Date expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.deleted
     *
     * @return the value of users.deleted
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.deleted
     *
     * @param deleted the value for users.deleted
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated Fri Mar 19 19:40:52 JST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}