/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package jp.co.suyama.menu.deliver.controller.interfaces;

import jp.co.suyama.menu.deliver.model.auto.FavoriteArticleIsAddedResponse;
import jp.co.suyama.menu.deliver.model.auto.FavoriteMenuIsAddedResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-24T14:39:40.139+09:00")

@Validated
@Api(value = "favorite", description = "the favorite API")
@RequestMapping(value = "")
public interface FavoriteApi {

    @ApiOperation(value = "記事のお気に入り追加状態を取得", nickname = "favoriteArticleIsAdded", notes = "記事がお気に入りに追加されているかを確認する 認証必須 ", response = FavoriteArticleIsAddedResponse.class, tags={ "Favorite", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "通信成功時の返却値", response = FavoriteArticleIsAddedResponse.class),
        @ApiResponse(code = 400, message = "200以外の時のは通信失敗をクライアントに通達") })
    @RequestMapping(value = "/favorite/article/item",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<FavoriteArticleIsAddedResponse> favoriteArticleIsAdded(@NotNull @ApiParam(value = "記事ID", required = true) @Valid @RequestParam(value = "id", required = true) Integer id);


    @ApiOperation(value = "献立のお気に入り追加状態を取得", nickname = "favoriteMenuIsAdded", notes = "献立がお気に入りに追加されているかを確認する 認証必須 ", response = FavoriteMenuIsAddedResponse.class, tags={ "Favorite", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "通信成功時の返却値", response = FavoriteMenuIsAddedResponse.class),
        @ApiResponse(code = 400, message = "200以外の時のは通信失敗をクライアントに通達") })
    @RequestMapping(value = "/favorite/menu/item",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<FavoriteMenuIsAddedResponse> favoriteMenuIsAdded(@NotNull @ApiParam(value = "献立ID", required = true) @Valid @RequestParam(value = "id", required = true) Integer id);

}
