/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package jp.co.suyama.menu.deliver.controller.interfaces;

import jp.co.suyama.menu.deliver.model.auto.RecommendMetaDataResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-19T19:06:35.752+09:00")

@Validated
@Api(value = "recommend", description = "the recommend API")
@RequestMapping(value = "")
public interface RecommendApi {

    @ApiOperation(value = "おすすめ情報表示パラメタを取得", nickname = "getRecommendMeta", notes = "トップのおすすめ情報を表示するための情報を取得 表示画像や表示情報を取得 認証不要 ", response = RecommendMetaDataResponse.class, tags={ "Recommend", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "通信成功時の返却値", response = RecommendMetaDataResponse.class),
        @ApiResponse(code = 400, message = "200以外の時のは通信失敗をクライアントに通達") })
    @RequestMapping(value = "/recommend/meta",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<RecommendMetaDataResponse> getRecommendMeta();

}
